# Generated by Django 3.1.7 on 2021-03-14 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listingscomments_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='users_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
