# Generated by Django 3.1.7 on 2021-03-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210314_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlistings',
            old_name='users_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='listingsbids',
            old_name='users_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='listingscomments',
            old_name='users',
            new_name='user',
        ),
    ]
