# Generated by Django 3.1.7 on 2021-04-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210422_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlistings',
            old_name='price',
            new_name='startingPrice',
        ),
    ]
