# Generated by Django 3.1.7 on 2021-04-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210423_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
