# Generated by Django 3.1.7 on 2021-04-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210423_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='startingPrice',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='topBid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingsbids',
            name='bids',
            field=models.FloatField(),
        ),
    ]
