# Generated by Django 3.1.7 on 2021-04-24 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210424_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='watchers',
            field=models.ManyToManyField(blank=True, null=True, related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
