# Generated by Django 3.1.7 on 2021-04-24 22:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auctionlistings_watchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
