# Generated by Django 3.1.7 on 2021-04-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210424_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
