# Generated by Django 3.1.7 on 2021-04-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210425_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='buyer',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
