# Generated by Django 3.1.7 on 2021-04-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auctionlistings_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='buyer',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
