# Generated by Django 3.1.7 on 2021-04-25 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20210425_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='buyer',
            field=models.ForeignKey(blank=True, max_length=80, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bought_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='my_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
