# Generated by Django 3.1.7 on 2021-04-23 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210422_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='topBid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True),
        ),
        migrations.AlterField(
            model_name='listingsbids',
            name='listing_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auctionlistings'),
        ),
        migrations.AlterField(
            model_name='listingscomments',
            name='listing_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_comments', to='auctions.auctionlistings'),
        ),
    ]
