# Generated by Django 3.1.7 on 2021-04-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210425_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Books', 'Books'), ('Business & Industrial', 'Business & Industrial'), ('Clothing, Shoes & Accessories', 'Clothing, Shoes & Accessories'), ('Collectibles', 'Collectibles'), ('Consumer Electronics', 'Consumer Electronics'), ('Crafts', 'Crafts'), ('Dolls & Bears', 'Dolls & Bears'), ('Home & Garden', 'Home & Garden'), ('Motors', 'Motors'), ('Pet Supplies', 'Pet Supplies'), ('Sporting Goods', 'Sporting Goods'), ('Sports Mem, Cards & Fan Shop', 'Sports Mem, Cards & Fan Shop'), ('Toys & Hobbies', 'Toys & Hobbies'), ('Antiques', 'Antiques'), ('Computers/Tablets & Networking', 'Computers/Tablets & Networking'), ('Other', 'Other')], max_length=200)),
            ],
        ),
    ]
